"""
Generated by Leslie in shanghai @leadrive
time: 2019年4月10日13:04:10
Version 2.5

kep o mvi
"""
from packages.basic.basic_functions import *
from packages.basic.log import Set_Log

import os
import sys
import logging


#创建日志
log_name = 'run_log.log'
log_path = os.path.abspath('.')
log = Set_Log(log_name, log_path, logger_name='Com_cfg')

def Modi_Com_cfg(str_bswtimebase, dbcname):
	"""configure Time period factor for each messages 
	according to timebase set in Confiutation.CSV file"""
	
	#判断BSW时基设置是否正确，仅为1和10，否则报错退出程序
	if str_bswtimebase == '1' or str_bswtimebase == '10':
		ori_file_name = 'pending_file\\Com_cfg.c'
		new_file_name = 'processed_file\\Com_cfg.c'
		idandNameDic = []
		idandTimeDic = []
		
		#读取DBC文件，获取message的ID和name以及ID和发送周期信息
		dbclines = Read_File(dbcname)
		print("# Read file " + dbcname + "successfully.")
		log.info("# Read file " + dbcname + "successfully.")
		idandNameDic = OutIdandName(dbclines)
		print('# information obtained from DBC file: id and name: ')
		log.info('# information obtained from DBC file: id and name.')
		print('  ', idandNameDic)
		idandTimeDic = OutIdandTime(dbclines)
		print('# information obtained from DBC file: id and time: ')
		log.info('# information obtained from DBC file: id and time.')
		print('  ', idandTimeDic)
		
		#读取C文件，依据关键字TimePeriodFact，根据BSWTimebase修改周期时间系数TimePeriodFact
		lines = Read_File(ori_file_name)
		for i in range(len(lines)):
			#print(str(i))
			for idkey in idandNameDic.keys():
				if (idandNameDic[idkey] in lines[i]) and ('CONST' in lines[i]):
					count = i
					num = 0
					while num != 2:
						count = Search_Substring(lines, 'TimePeriodFact', start_pos=count)
						del lines[count]
						timefact = int(int(idandTimeDic[idkey])/int(str_bswtimebase))
						#print(str(timefact))
						#print(str(count))
						lines.insert(count, '	' + str(timefact) + ',   /* TimePeriodFact   */\n')
						i = count + 1
						count += 1
						num += 1
						log.info("# Correct "+ idandNameDic[idkey] +\
						" TimePeriodfact " + idandTimeDic[idkey] + " successfully.")
						print("# Correct "+ idandNameDic[idkey] +\
						" TimePeriodfact " + idandTimeDic[idkey] + " successfully.")
		
		#写入文件
		Write_File(new_file_name, lines)
		log.info("# Creat a new file in pending_file folder successfully.")
		print("# Creat a new file in pending_file folder successfully.")
		#Show_File(new_file_name)
	else:
		log.info("BSWTimeBase only can be set as 1 or 10. Please recheck for it.")
		print("BSWTimeBase only can be set as 1 or 10. Please recheck for it.")
		sys.stdin.readline()
		exit()

	
def OutIdandName(dbclines):
	"""output the message information in the format of dic"""
	
	idandNameDic = []
	header_string = 'BO_'
	BO_lines = Search_Str(dbclines, header_string)
	idandNameDic = OutIDandAttriDic(BO_lines, 1, 2)
	
	return idandNameDic
	
def OutIdandTime(dbclines):
	"""output the message information in the format of dic"""
	
	idandTimeDic = []
	header_string = 'BA_'
	str_condition = '"GenMsgCycleTime"'
	BA_lines = Search_Str(dbclines, header_string, condi_code=str_condition)
	idandTimeDic = OutIDandAttriDic(BA_lines, 3, 4)
	
	return idandTimeDic
	
	
	
	
	
	
	
	
	
	
	
	
	
