"""
Generated by Leslie in shanghai @leadrive
Version: 2.5
Time: 2019年4月10日09:36:18

Kep o mvi
"""

from packages.basic.basic_functions import *
from packages.basic.log import Set_Log

import os
import csv
import logging

#创建日志
log_name = 'run_log.log'
log_path = os.path.abspath('.')
log = Set_Log(log_name, log_path, logger_name='Can_Cfg')

def Modi_Can_Cfg(str_CAN_mode):
	"""对文件Can_Cfg.h处理，使其依照扩展帧进行配置本头文件"""
	
	file_name = 'pending_file\\Can_Cfg.h'
	
	if str_CAN_mode == '1':
		lines = Read_File(file_name)
		log.info("# Read source file successfully:" + file_name)
		print("# Read source file successfully:" + file_name)
		
		lines = Comment_out(lines)
		
		lines = Frame_change(lines)
		log.info("# Frame Type is changed correctly.")
		
		Write_File('processed_file\\Can_Cfg.h', lines)
		log.info("# Creat a new file in pending_file folder successfully.")
		print("# Creat a new file in pending_file folder successfully.")
		
	else:
		log.info("# Stardard mode, file, 'Can_Cfg.h' is no need to be modified.")
		print("# Stardard mode, file, 'Can_Cfg.h' is no need to be modified.")
		

def Comment_out(lines):
	"""注释代码段'typedef uint16 Can_IdType;'"""
	
	comm_out_code = 'typedef uint16 Can_IdType;'
	lines = Comm_Out(lines, comm_out_code)
	log.info("# Codes,'typedef uint16 Can_IdType;', is commented out successfully. ")
	print("# Codes,'typedef uint16 Can_IdType;', is commented out successfully. ")
	
	return lines
	
	
def Frame_change(lines, str_sear_code='#define CAN_EXTENDED_ID'):
	"""change Frame type from Standard mode into Extended mode."""
	
	count = Search_Substring(lines, str_sear_code)
	ori_mode = 'STD_OFF'
	new_mode = 'STD_ON'
		
	if ori_mode in lines[count]:
		lines[count]=lines[count].replace(ori_mode, new_mode)
		print("# Frame Type is changed correctly.", lines[count])
	
	return lines
	
	
		

