'''
Generated by Leslie in shanghai@leadrive
Time: 2019年4月17日15:26:49
Version 3.3

Kep o mvi
'''
from packages.basic.basic_functions import *
from packages.for_file.modi_Com_cfg.py import OutIdandName
 
import os
import sys
import time
 
def Modi_rte_comc(dbc):
	'''处理文件rte_com.c'''
	
	
