"""
Generated by leslie in shanghai, @leadrive.
Version 2.0
name: modi_Com_Cbk_Adap.py
time: 2019年3月21日14:28:01

kep o mvi
"""
import os
import sys
import logging

'''
#得到当前目录途径
thdir_path = os.path.abspath('.')
print(thdir_path)

#得到上一级目录途径
secdir_path = os.path.abspath('..')
print(secdir_path)

#得到上上级目录途径
firdir_path = os.path.dirname(secdir_path)
print(firdir_path)
'''

'''
#添加目录
file_name = '123.txt'

pat = os.path.join(firdir_path,file_name)
print(pat)
'''
def Set_Log(logname,logpath=os.path.dirname(os.path.abspath('..')),logger_name="test_logger"):
	
	# 创建一个日志记录器
	log = logging.getLogger(logger_name)
	log.setLevel(logging.INFO)

	file_name= logpath + "\\" + logname
    
	# 创建一个日志处理器
	## 这里需要正确填写路径和文件名，拼成一个字符串，最终生成一个log文件
	logHandler = logging.FileHandler(filename = file_name)
	
	## 设置日志级别
	logHandler.setLevel(logging.DEBUG)
	
	# 创建一个日志格式器
	formats = logging.Formatter('%(asctime)s %(levelname)s: %(message)s',
				datefmt='[%Y/%m/%d %I:%M:%S]')

	# 将日志格式器添加到日志处理器中
	logHandler.setFormatter(formats)

	# 将日志处理器添加到日志记录器中
	log.addHandler(logHandler)
	
	return log
    
    
    
    
